I will listen to the wind and waves... #speaker:Fhinn #layout:UI_Dialogue_LayoutFhinn
And carry their message with me...
For we trust the current of life...
So that in death, we may be reunited again.