//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Systems/Input System/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""18c423a6-4142-4473-b5d0-b5a1074b0d4e"",
            ""actions"": [
                {
                    ""name"": ""SprintStart"",
                    ""type"": ""Button"",
                    ""id"": ""6c0f8c1e-b1a8-4126-bcce-f34fcf1fb2b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SprintStop"",
                    ""type"": ""Button"",
                    ""id"": ""6c92a781-903f-4f12-8045-7999c5521109"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WaterGrab"",
                    ""type"": ""Button"",
                    ""id"": ""9cf827c5-a0d2-44b8-b188-e7ccafd9c459"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WaterTrow"",
                    ""type"": ""Button"",
                    ""id"": ""14afd481-5d3e-4e77-aa42-ae9e058e6519"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeverLeft"",
                    ""type"": ""Button"",
                    ""id"": ""6be12d5a-9b3e-436e-8965-f75e3a7a0e49"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeverRight"",
                    ""type"": ""Button"",
                    ""id"": ""7ecf0af1-e52a-4f8d-ad30-cb48656ecd4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeverLetGo"",
                    ""type"": ""Button"",
                    ""id"": ""c93a882a-688f-4bc4-8c04-ca2fa9a217a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""71a46188-6461-40a7-a0d7-431093f676b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""664fadf2-aa0e-4677-abdc-30fa5c4dc13d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1f444af8-724e-41e6-84f8-c7a2561a9c69"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SprintStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85392e91-b3bf-44d8-ab0e-25a8674dd640"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SprintStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2149c629-1fa2-4ded-97a2-f550f80d38d1"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SprintStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40ed4901-aca6-45a0-8b62-ba38dd09ab95"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SprintStop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4cc1f74d-071e-4d54-a0b4-a5ecd286295c"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SprintStop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2bf301e-498d-4066-9fdf-db382da65208"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SprintStop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e33a82b3-bd85-4766-a80f-8d55116bf64a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WaterGrab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51e02657-ca02-4459-a48a-84655792171e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WaterGrab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a82887c-3363-42e5-96ee-7f555e3671d7"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WaterTrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb3963e6-ddd6-4c71-a424-c34826f1b363"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WaterTrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4f09046-b8e7-43d6-9dbe-99850a759b32"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WaterTrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c53e2752-625e-4eda-b0a0-f34bba0581c1"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WaterTrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""583d1e20-e37d-4373-b6fe-506769e1e320"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeverLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""266a2b93-4a56-45b3-8d1f-86721acfb89a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeverLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c5e2989-668f-4211-b9ff-7fa2a8b515c5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeverLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c912cfc-8978-4650-b59c-50ec68a86a5e"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeverRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1dee03b3-5dcb-4d82-8b40-49360fc9cea3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeverRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e994b177-7f9c-4960-a27f-1a19f517afa0"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeverRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ad51ce6-cc27-4882-9c28-cd0fcd6d36dd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeverLetGo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d4635a7-f00d-48e8-8f10-fc9fcc4d12fb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeverLetGo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20a3014b-6a7d-423d-9f28-3d2ff2521d1e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeverLetGo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25a9e741-9070-48a4-9c97-f27792b0340c"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeverLetGo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""400e185f-474d-4d7e-828a-0967c18af07d"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeverLetGo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de7c6271-1e10-4f4f-a299-f301c6a6c066"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeverLetGo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""321c8ec6-53a6-4559-95af-58a893eff852"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0e6dcf2-a517-4109-ba3f-a02e48028996"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5915e975-1a79-4e18-92fd-79b46ea81ceb"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af6305ec-4b24-466c-8330-3d94552aa05e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""WorldUI"",
            ""id"": ""82443695-8add-434b-8496-002fc5b8b727"",
            ""actions"": [
                {
                    ""name"": ""Dialogue"",
                    ""type"": ""Button"",
                    ""id"": ""d79addb7-e29f-4195-88e8-73ed59fa9448"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""91c67a05-d4e2-4984-bbd1-e471ae44220e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""f3e1fff9-4d91-4824-ad9c-4c384f22a568"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ad9be491-1ade-4b5b-9659-9ca7ce02ff2c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7905ac27-d66f-4375-b726-0cd8bfc323b6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61a02636-5c52-4e39-85f4-7d11cfeb462e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b983ce54-a3fb-4ab8-a6f7-ff45c36c2c34"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03367b8c-ac66-4653-b9c5-485c43321026"",
                    ""path"": ""<DualShockGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fdf922b-1b67-4849-8113-816b039ea55f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d88c058-ec0a-4a7b-a7f0-c17c1ef971d3"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MenuUI"",
            ""id"": ""fe1c8577-a0d1-4b69-ba02-81db95c883e0"",
            ""actions"": [
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""eb2e151f-3b08-4a02-a97b-f0f82f5c756d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""9df9e623-409d-413f-baa6-147215ea6531"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""614b709a-34e4-4047-bb94-2e14ee668d1c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""bb771700-7ec1-42d7-aff6-3bf79e01e421"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""d7f5746c-484f-41de-96a2-2523b53518cd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e6b525b4-831d-40b0-9732-0577a51bedef"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""48c68bb7-ab75-4ead-a58b-e2ddac627aa5"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b53dcf76-e31b-453e-865f-63419317eeab"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""edfa1a61-a56a-4a65-b3aa-d87c5e29d9ba"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""609e58b4-a2dd-4ae1-b7e4-5be6e07d35a7"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3de967d4-c5b1-4f05-b9d2-693486683357"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2451dcd3-a3d0-4eaa-80cc-9980ab9e1906"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""790e72b3-d32a-478e-897d-12b1620e5ae0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""b2a557ec-8603-497a-a8a8-f4ac1ca7aa26"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7b934283-be09-410a-a46b-79a4c6eec93c"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a8c0254c-ba05-43e2-b9ec-ace3f16dec83"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f0c6af7d-11b8-46c6-9d45-f42ba01b9137"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""45ad5aa2-836d-458a-aeda-38680b528483"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""a8952922-b246-4f6d-9f9f-86eaee946101"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f85d9e81-68cf-4342-85cf-59cb52c8126b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7a92a760-a9af-46ec-8490-cffd1291da83"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f803c099-5661-4164-b86a-d677644eb964"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d668ecc5-df93-445e-919d-51269dcef6eb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""D-Pad"",
                    ""id"": ""55af9e7d-9f75-46ab-a9f8-72d1a8f0bb93"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""98a2318e-5849-448a-be19-7eba9f5cb714"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ef29c231-2eb2-49f1-9cb3-d8a4ca01d484"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e36508e6-d8bd-407b-a56c-8c5521110276"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""044fd490-047a-4751-b28c-0410e67c895f"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f8b44b18-142d-43d2-80fb-4d872031f087"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05df5d5e-c54a-47e5-9601-752d9c69a74b"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_SprintStart = m_Player.FindAction("SprintStart", throwIfNotFound: true);
        m_Player_SprintStop = m_Player.FindAction("SprintStop", throwIfNotFound: true);
        m_Player_WaterGrab = m_Player.FindAction("WaterGrab", throwIfNotFound: true);
        m_Player_WaterTrow = m_Player.FindAction("WaterTrow", throwIfNotFound: true);
        m_Player_LeverLeft = m_Player.FindAction("LeverLeft", throwIfNotFound: true);
        m_Player_LeverRight = m_Player.FindAction("LeverRight", throwIfNotFound: true);
        m_Player_LeverLetGo = m_Player.FindAction("LeverLetGo", throwIfNotFound: true);
        m_Player_Back = m_Player.FindAction("Back", throwIfNotFound: true);
        m_Player_Select = m_Player.FindAction("Select", throwIfNotFound: true);
        // WorldUI
        m_WorldUI = asset.FindActionMap("WorldUI", throwIfNotFound: true);
        m_WorldUI_Dialogue = m_WorldUI.FindAction("Dialogue", throwIfNotFound: true);
        m_WorldUI_Pause = m_WorldUI.FindAction("Pause", throwIfNotFound: true);
        m_WorldUI_Back = m_WorldUI.FindAction("Back", throwIfNotFound: true);
        // MenuUI
        m_MenuUI = asset.FindActionMap("MenuUI", throwIfNotFound: true);
        m_MenuUI_Point = m_MenuUI.FindAction("Point", throwIfNotFound: true);
        m_MenuUI_Submit = m_MenuUI.FindAction("Submit", throwIfNotFound: true);
        m_MenuUI_Navigate = m_MenuUI.FindAction("Navigate", throwIfNotFound: true);
        m_MenuUI_Cancel = m_MenuUI.FindAction("Cancel", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_SprintStart;
    private readonly InputAction m_Player_SprintStop;
    private readonly InputAction m_Player_WaterGrab;
    private readonly InputAction m_Player_WaterTrow;
    private readonly InputAction m_Player_LeverLeft;
    private readonly InputAction m_Player_LeverRight;
    private readonly InputAction m_Player_LeverLetGo;
    private readonly InputAction m_Player_Back;
    private readonly InputAction m_Player_Select;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @SprintStart => m_Wrapper.m_Player_SprintStart;
        public InputAction @SprintStop => m_Wrapper.m_Player_SprintStop;
        public InputAction @WaterGrab => m_Wrapper.m_Player_WaterGrab;
        public InputAction @WaterTrow => m_Wrapper.m_Player_WaterTrow;
        public InputAction @LeverLeft => m_Wrapper.m_Player_LeverLeft;
        public InputAction @LeverRight => m_Wrapper.m_Player_LeverRight;
        public InputAction @LeverLetGo => m_Wrapper.m_Player_LeverLetGo;
        public InputAction @Back => m_Wrapper.m_Player_Back;
        public InputAction @Select => m_Wrapper.m_Player_Select;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @SprintStart.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprintStart;
                @SprintStart.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprintStart;
                @SprintStart.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprintStart;
                @SprintStop.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprintStop;
                @SprintStop.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprintStop;
                @SprintStop.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprintStop;
                @WaterGrab.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWaterGrab;
                @WaterGrab.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWaterGrab;
                @WaterGrab.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWaterGrab;
                @WaterTrow.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWaterTrow;
                @WaterTrow.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWaterTrow;
                @WaterTrow.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWaterTrow;
                @LeverLeft.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeverLeft;
                @LeverLeft.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeverLeft;
                @LeverLeft.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeverLeft;
                @LeverRight.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeverRight;
                @LeverRight.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeverRight;
                @LeverRight.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeverRight;
                @LeverLetGo.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeverLetGo;
                @LeverLetGo.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeverLetGo;
                @LeverLetGo.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeverLetGo;
                @Back.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBack;
                @Select.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelect;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SprintStart.started += instance.OnSprintStart;
                @SprintStart.performed += instance.OnSprintStart;
                @SprintStart.canceled += instance.OnSprintStart;
                @SprintStop.started += instance.OnSprintStop;
                @SprintStop.performed += instance.OnSprintStop;
                @SprintStop.canceled += instance.OnSprintStop;
                @WaterGrab.started += instance.OnWaterGrab;
                @WaterGrab.performed += instance.OnWaterGrab;
                @WaterGrab.canceled += instance.OnWaterGrab;
                @WaterTrow.started += instance.OnWaterTrow;
                @WaterTrow.performed += instance.OnWaterTrow;
                @WaterTrow.canceled += instance.OnWaterTrow;
                @LeverLeft.started += instance.OnLeverLeft;
                @LeverLeft.performed += instance.OnLeverLeft;
                @LeverLeft.canceled += instance.OnLeverLeft;
                @LeverRight.started += instance.OnLeverRight;
                @LeverRight.performed += instance.OnLeverRight;
                @LeverRight.canceled += instance.OnLeverRight;
                @LeverLetGo.started += instance.OnLeverLetGo;
                @LeverLetGo.performed += instance.OnLeverLetGo;
                @LeverLetGo.canceled += instance.OnLeverLetGo;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // WorldUI
    private readonly InputActionMap m_WorldUI;
    private IWorldUIActions m_WorldUIActionsCallbackInterface;
    private readonly InputAction m_WorldUI_Dialogue;
    private readonly InputAction m_WorldUI_Pause;
    private readonly InputAction m_WorldUI_Back;
    public struct WorldUIActions
    {
        private @PlayerInputActions m_Wrapper;
        public WorldUIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Dialogue => m_Wrapper.m_WorldUI_Dialogue;
        public InputAction @Pause => m_Wrapper.m_WorldUI_Pause;
        public InputAction @Back => m_Wrapper.m_WorldUI_Back;
        public InputActionMap Get() { return m_Wrapper.m_WorldUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WorldUIActions set) { return set.Get(); }
        public void SetCallbacks(IWorldUIActions instance)
        {
            if (m_Wrapper.m_WorldUIActionsCallbackInterface != null)
            {
                @Dialogue.started -= m_Wrapper.m_WorldUIActionsCallbackInterface.OnDialogue;
                @Dialogue.performed -= m_Wrapper.m_WorldUIActionsCallbackInterface.OnDialogue;
                @Dialogue.canceled -= m_Wrapper.m_WorldUIActionsCallbackInterface.OnDialogue;
                @Pause.started -= m_Wrapper.m_WorldUIActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_WorldUIActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_WorldUIActionsCallbackInterface.OnPause;
                @Back.started -= m_Wrapper.m_WorldUIActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_WorldUIActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_WorldUIActionsCallbackInterface.OnBack;
            }
            m_Wrapper.m_WorldUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Dialogue.started += instance.OnDialogue;
                @Dialogue.performed += instance.OnDialogue;
                @Dialogue.canceled += instance.OnDialogue;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
            }
        }
    }
    public WorldUIActions @WorldUI => new WorldUIActions(this);

    // MenuUI
    private readonly InputActionMap m_MenuUI;
    private IMenuUIActions m_MenuUIActionsCallbackInterface;
    private readonly InputAction m_MenuUI_Point;
    private readonly InputAction m_MenuUI_Submit;
    private readonly InputAction m_MenuUI_Navigate;
    private readonly InputAction m_MenuUI_Cancel;
    public struct MenuUIActions
    {
        private @PlayerInputActions m_Wrapper;
        public MenuUIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Point => m_Wrapper.m_MenuUI_Point;
        public InputAction @Submit => m_Wrapper.m_MenuUI_Submit;
        public InputAction @Navigate => m_Wrapper.m_MenuUI_Navigate;
        public InputAction @Cancel => m_Wrapper.m_MenuUI_Cancel;
        public InputActionMap Get() { return m_Wrapper.m_MenuUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuUIActions set) { return set.Get(); }
        public void SetCallbacks(IMenuUIActions instance)
        {
            if (m_Wrapper.m_MenuUIActionsCallbackInterface != null)
            {
                @Point.started -= m_Wrapper.m_MenuUIActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_MenuUIActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_MenuUIActionsCallbackInterface.OnPoint;
                @Submit.started -= m_Wrapper.m_MenuUIActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_MenuUIActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_MenuUIActionsCallbackInterface.OnSubmit;
                @Navigate.started -= m_Wrapper.m_MenuUIActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_MenuUIActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_MenuUIActionsCallbackInterface.OnNavigate;
                @Cancel.started -= m_Wrapper.m_MenuUIActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_MenuUIActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_MenuUIActionsCallbackInterface.OnCancel;
            }
            m_Wrapper.m_MenuUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
            }
        }
    }
    public MenuUIActions @MenuUI => new MenuUIActions(this);
    public interface IPlayerActions
    {
        void OnSprintStart(InputAction.CallbackContext context);
        void OnSprintStop(InputAction.CallbackContext context);
        void OnWaterGrab(InputAction.CallbackContext context);
        void OnWaterTrow(InputAction.CallbackContext context);
        void OnLeverLeft(InputAction.CallbackContext context);
        void OnLeverRight(InputAction.CallbackContext context);
        void OnLeverLetGo(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
    public interface IWorldUIActions
    {
        void OnDialogue(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
    public interface IMenuUIActions
    {
        void OnPoint(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnNavigate(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
    }
}
